# Generated by Django 3.2.5 on 2022-08-24 19:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='PetRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(blank=True, max_length=30, verbose_name='Raza')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='pets.petspecies', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ('species', 'race'),
                'default_related_name': 'races',
                'unique_together': {('species', 'race')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Hembra'), ('M', 'Macho')], max_length=1, null=True, verbose_name='Sexo')),
                ('birthday', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Fecha de nacimiento')),
                ('annotations', models.TextField(blank=True, null=True, verbose_name='Anotaciones')),
                ('deceased', models.BooleanField(blank=True, default=False, verbose_name='¿Ha fallecido?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.petrace', verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ('-created_at',),
                'default_related_name': 'pets',
            },
        ),
    ]
