# Generated by Django 3.2.5 on 2022-07-14 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PetRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(blank=True, max_length=30, null=True, verbose_name='Raza')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='pets.petspecies', verbose_name='Especie')),
            ],
            options={
                'unique_together': {('species', 'race')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Hembra'), ('M', 'Macho')], max_length=1, null=True, verbose_name='Sexo')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Cumpleaños')),
                ('annotations', models.TextField(blank=True, null=True, verbose_name='Anotaciones')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.petrace', verbose_name='Raza')),
            ],
        ),
    ]
