# Generated by Django 3.2.5 on 2022-07-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'default_related_name': 'pets'},
        ),
        migrations.AlterModelOptions(
            name='petrace',
            options={'default_related_name': 'races'},
        ),
    ]
