# Generated by Django 3.2.5 on 2022-07-14 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20220714_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'default_related_name': 'pets', 'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
