# Generated by Django 3.2.5 on 2022-07-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20220714_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'default_related_name': 'pets', 'ordering': ('-created_at',), 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='petrace',
            options={'default_related_name': 'races', 'ordering': ('species__name', 'race'), 'verbose_name': 'Raza', 'verbose_name_plural': 'Razas'},
        ),
        migrations.AlterModelOptions(
            name='petspecies',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AddField(
            model_name='pet',
            name='deceased',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
