# Generated by Django 3.2.5 on 2022-07-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20220721_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='deceased',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Ha fallecido?'),
        ),
    ]
