# Generated by Django 3.2.5 on 2022-07-14 15:32

from django.db import migrations
import petclinic.models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', petclinic.models.UserManager()),
            ],
        ),
    ]
