# Generated by Django 3.2.5 on 2022-07-14 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_auto_20220714_2348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('annotations', models.TextField(blank=True, null=True, verbose_name='Anotaciones')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='pets.pet', verbose_name='Mascota')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'default_related_name': 'appointments',
            },
        ),
    ]
