# Generated by Django 3.2.5 on 2022-08-24 19:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha y hora')),
                ('annotations', models.TextField(blank=True, null=True, verbose_name='Anotaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ('-date',),
                'default_related_name': 'appointments',
            },
        ),
    ]
