# Generated by Django 3.2.5 on 2022-07-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20220714_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'default_related_name': 'appointments', 'ordering': ('-date',), 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='annotations',
            field=models.TextField(null=True, verbose_name='Anotaciones'),
        ),
    ]
