# Generated by Django 3.2.5 on 2022-07-21 23:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='annotations',
            field=models.TextField(blank=True, null=True, verbose_name='Anotaciones'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.now)], verbose_name='Fecha y hora'),
        ),
    ]
