# Generated by Django 3.2.5 on 2022-07-22 17:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20220722_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Fecha y hora'),
        ),
    ]
